export const LOGIN_SUC = "LOGIN_SUC";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQ = "LOGIN_REQ";
export const LOGOUT = "LOGOUT";
export const LOAD_PROF = "LOAD_PROF";


export const HOME_VIDEOS_SUCC = "HOME_VIDEOS_SUCC";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQ = "HOME_VIDEOS_REQ";


export const SELECTED_VIDEO_REQ = "SELECTED_VIDEO_REQ"
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS"
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL"


export const CHANNEL_DETAILS_REQ = "CHANNEL_DETAILS_REQ"
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"


export const GET_SUBSCRIPTION_STATUS ="GET_SUBSCRIPTION_STATUS"

export const COMMENT_LIST_REQ = "COMMENT_LIST_REQ"
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS"
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL"

export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS" 
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL" 

export const SEARCH_VIDEO_REQ = "SEARCH_VIDEO_REQ" 
export const SEARCH_VIDEO_FAIL = "SEARCH_VIDEO_FAIL" 
export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS" 

export const SUBSCRIPTION_CHANNEL_REQ = "SUBSCRIPTION_CHANNEL_REQ" 
export const SUBSCRIPTION_CHANNEL_FAIL = "SUBSCRIPTION_CHANNEL_FAIL" 
export const SUBSCRIPTION_CHANNEL_SUCCESS = "SUBSCRIPTION_CHANNEL_SUCCESS" 

export const CHANNEL_VIDEO_REQ = "CHANNEL_VIDEO_REQ" 
export const CHANNEL_VIDEO_FAIL = "CHANNEL_VIDEO_FAIL" 
export const CHANNEL_VIDEO_SUCCESS = "CHANNEL_VIDEO_SUCCESS" 

export const GET_LIKED_VIDEOS_REQ = "GET_LIKED_VIDEOS_REQ" 
export const GET_LIKED_VIDEOS_FAIL = "GET_LIKED_VIDEOS_FAIL" 
export const GET_LIKED_VIDEOS_SUCCESS = "GET_LIKED_VIDEOS_SUCCESS" 